//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GastroTransfer.LsiService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ICWSSoap", Namespace="ICWS")]
    public partial class ICWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PobierzProduktyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UtworzDokumentProdukcjiOperationCompleted;
        
        private System.Threading.SendOrPostCallback UtworzDokumentyPrzesunieciaMagazynowegoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzMagazynyOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzGrupyTowaroweOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzPotrawyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UtworzDokumentRozchodowyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ICWS() {
            this.Url = global::GastroTransfer.Properties.Settings.Default.GastroTransfer_LsiService_ICWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PobierzProduktyCompletedEventHandler PobierzProduktyCompleted;
        
        /// <remarks/>
        public event UtworzDokumentProdukcjiCompletedEventHandler UtworzDokumentProdukcjiCompleted;
        
        /// <remarks/>
        public event UtworzDokumentyPrzesunieciaMagazynowegoCompletedEventHandler UtworzDokumentyPrzesunieciaMagazynowegoCompleted;
        
        /// <remarks/>
        public event PobierzMagazynyCompletedEventHandler PobierzMagazynyCompleted;
        
        /// <remarks/>
        public event PobierzGrupyTowaroweCompletedEventHandler PobierzGrupyTowaroweCompleted;
        
        /// <remarks/>
        public event PobierzPotrawyCompletedEventHandler PobierzPotrawyCompleted;
        
        /// <remarks/>
        public event UtworzDokumentRozchodowyCompletedEventHandler UtworzDokumentRozchodowyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ICWSPobierzProdukty", RequestNamespace="ICWS", ResponseNamespace="ICWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PobierzProduktyResult PobierzProdukty(PobierzProduktyRequestDataRequestObject RequestData) {
            object[] results = this.Invoke("PobierzProdukty", new object[] {
                        RequestData});
            return ((PobierzProduktyResult)(results[0]));
        }
        
        /// <remarks/>
        public void PobierzProduktyAsync(PobierzProduktyRequestDataRequestObject RequestData) {
            this.PobierzProduktyAsync(RequestData, null);
        }
        
        /// <remarks/>
        public void PobierzProduktyAsync(PobierzProduktyRequestDataRequestObject RequestData, object userState) {
            if ((this.PobierzProduktyOperationCompleted == null)) {
                this.PobierzProduktyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzProduktyOperationCompleted);
            }
            this.InvokeAsync("PobierzProdukty", new object[] {
                        RequestData}, this.PobierzProduktyOperationCompleted, userState);
        }
        
        private void OnPobierzProduktyOperationCompleted(object arg) {
            if ((this.PobierzProduktyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzProduktyCompleted(this, new PobierzProduktyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ICWSUtworzDokumentProdukcji", RequestNamespace="ICWS", ResponseNamespace="ICWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UtworzDokumentProdukcjiResult UtworzDokumentProdukcji(UtworzDokumentProdukcjiRequestDataRequestObject RequestData) {
            object[] results = this.Invoke("UtworzDokumentProdukcji", new object[] {
                        RequestData});
            return ((UtworzDokumentProdukcjiResult)(results[0]));
        }
        
        /// <remarks/>
        public void UtworzDokumentProdukcjiAsync(UtworzDokumentProdukcjiRequestDataRequestObject RequestData) {
            this.UtworzDokumentProdukcjiAsync(RequestData, null);
        }
        
        /// <remarks/>
        public void UtworzDokumentProdukcjiAsync(UtworzDokumentProdukcjiRequestDataRequestObject RequestData, object userState) {
            if ((this.UtworzDokumentProdukcjiOperationCompleted == null)) {
                this.UtworzDokumentProdukcjiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUtworzDokumentProdukcjiOperationCompleted);
            }
            this.InvokeAsync("UtworzDokumentProdukcji", new object[] {
                        RequestData}, this.UtworzDokumentProdukcjiOperationCompleted, userState);
        }
        
        private void OnUtworzDokumentProdukcjiOperationCompleted(object arg) {
            if ((this.UtworzDokumentProdukcjiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UtworzDokumentProdukcjiCompleted(this, new UtworzDokumentProdukcjiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ICWSUtworzDokumentyPrzesunieciaMagazynowego", RequestNamespace="ICWS", ResponseNamespace="ICWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UtworzDokumentyPrzesunieciaMagazynowegoResult UtworzDokumentyPrzesunieciaMagazynowego(UtworzDokumentyPrzesunieciaMagazynowegoRequestDataRequestObject RequestData) {
            object[] results = this.Invoke("UtworzDokumentyPrzesunieciaMagazynowego", new object[] {
                        RequestData});
            return ((UtworzDokumentyPrzesunieciaMagazynowegoResult)(results[0]));
        }
        
        /// <remarks/>
        public void UtworzDokumentyPrzesunieciaMagazynowegoAsync(UtworzDokumentyPrzesunieciaMagazynowegoRequestDataRequestObject RequestData) {
            this.UtworzDokumentyPrzesunieciaMagazynowegoAsync(RequestData, null);
        }
        
        /// <remarks/>
        public void UtworzDokumentyPrzesunieciaMagazynowegoAsync(UtworzDokumentyPrzesunieciaMagazynowegoRequestDataRequestObject RequestData, object userState) {
            if ((this.UtworzDokumentyPrzesunieciaMagazynowegoOperationCompleted == null)) {
                this.UtworzDokumentyPrzesunieciaMagazynowegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUtworzDokumentyPrzesunieciaMagazynowegoOperationCompleted);
            }
            this.InvokeAsync("UtworzDokumentyPrzesunieciaMagazynowego", new object[] {
                        RequestData}, this.UtworzDokumentyPrzesunieciaMagazynowegoOperationCompleted, userState);
        }
        
        private void OnUtworzDokumentyPrzesunieciaMagazynowegoOperationCompleted(object arg) {
            if ((this.UtworzDokumentyPrzesunieciaMagazynowegoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UtworzDokumentyPrzesunieciaMagazynowegoCompleted(this, new UtworzDokumentyPrzesunieciaMagazynowegoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ICWSPobierzMagazyny", RequestNamespace="ICWS", ResponseNamespace="ICWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PobierzMagazynyResult PobierzMagazyny() {
            object[] results = this.Invoke("PobierzMagazyny", new object[0]);
            return ((PobierzMagazynyResult)(results[0]));
        }
        
        /// <remarks/>
        public void PobierzMagazynyAsync() {
            this.PobierzMagazynyAsync(null);
        }
        
        /// <remarks/>
        public void PobierzMagazynyAsync(object userState) {
            if ((this.PobierzMagazynyOperationCompleted == null)) {
                this.PobierzMagazynyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzMagazynyOperationCompleted);
            }
            this.InvokeAsync("PobierzMagazyny", new object[0], this.PobierzMagazynyOperationCompleted, userState);
        }
        
        private void OnPobierzMagazynyOperationCompleted(object arg) {
            if ((this.PobierzMagazynyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzMagazynyCompleted(this, new PobierzMagazynyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ICWSPobierzGrupyTowarowe", RequestNamespace="ICWS", ResponseNamespace="ICWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PobierzGrupyTowaroweResult PobierzGrupyTowarowe() {
            object[] results = this.Invoke("PobierzGrupyTowarowe", new object[0]);
            return ((PobierzGrupyTowaroweResult)(results[0]));
        }
        
        /// <remarks/>
        public void PobierzGrupyTowaroweAsync() {
            this.PobierzGrupyTowaroweAsync(null);
        }
        
        /// <remarks/>
        public void PobierzGrupyTowaroweAsync(object userState) {
            if ((this.PobierzGrupyTowaroweOperationCompleted == null)) {
                this.PobierzGrupyTowaroweOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzGrupyTowaroweOperationCompleted);
            }
            this.InvokeAsync("PobierzGrupyTowarowe", new object[0], this.PobierzGrupyTowaroweOperationCompleted, userState);
        }
        
        private void OnPobierzGrupyTowaroweOperationCompleted(object arg) {
            if ((this.PobierzGrupyTowaroweCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzGrupyTowaroweCompleted(this, new PobierzGrupyTowaroweCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ICWSPobierzPotrawy", RequestNamespace="ICWS", ResponseNamespace="ICWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PobierzPotrawyResult PobierzPotrawy(PobierzPotrawyRequestDataRequestObject RequestData) {
            object[] results = this.Invoke("PobierzPotrawy", new object[] {
                        RequestData});
            return ((PobierzPotrawyResult)(results[0]));
        }
        
        /// <remarks/>
        public void PobierzPotrawyAsync(PobierzPotrawyRequestDataRequestObject RequestData) {
            this.PobierzPotrawyAsync(RequestData, null);
        }
        
        /// <remarks/>
        public void PobierzPotrawyAsync(PobierzPotrawyRequestDataRequestObject RequestData, object userState) {
            if ((this.PobierzPotrawyOperationCompleted == null)) {
                this.PobierzPotrawyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzPotrawyOperationCompleted);
            }
            this.InvokeAsync("PobierzPotrawy", new object[] {
                        RequestData}, this.PobierzPotrawyOperationCompleted, userState);
        }
        
        private void OnPobierzPotrawyOperationCompleted(object arg) {
            if ((this.PobierzPotrawyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzPotrawyCompleted(this, new PobierzPotrawyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ICWSUtworzDokumentRozchodowy", RequestNamespace="ICWS", ResponseNamespace="ICWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UtworzDokumentRozchodowyResult UtworzDokumentRozchodowy(UtworzDokumentRozchodowyRequestDataRequestObject RequestData) {
            object[] results = this.Invoke("UtworzDokumentRozchodowy", new object[] {
                        RequestData});
            return ((UtworzDokumentRozchodowyResult)(results[0]));
        }
        
        /// <remarks/>
        public void UtworzDokumentRozchodowyAsync(UtworzDokumentRozchodowyRequestDataRequestObject RequestData) {
            this.UtworzDokumentRozchodowyAsync(RequestData, null);
        }
        
        /// <remarks/>
        public void UtworzDokumentRozchodowyAsync(UtworzDokumentRozchodowyRequestDataRequestObject RequestData, object userState) {
            if ((this.UtworzDokumentRozchodowyOperationCompleted == null)) {
                this.UtworzDokumentRozchodowyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUtworzDokumentRozchodowyOperationCompleted);
            }
            this.InvokeAsync("UtworzDokumentRozchodowy", new object[] {
                        RequestData}, this.UtworzDokumentRozchodowyOperationCompleted, userState);
        }
        
        private void OnUtworzDokumentRozchodowyOperationCompleted(object arg) {
            if ((this.UtworzDokumentRozchodowyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UtworzDokumentRozchodowyCompleted(this, new UtworzDokumentRozchodowyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class PobierzProduktyRequestDataRequestObject {
        
        private int grupaTowIDField;
        
        private string magazynIDField;
        
        /// <remarks/>
        public int GrupaTowID {
            get {
                return this.grupaTowIDField;
            }
            set {
                this.grupaTowIDField = value;
            }
        }
        
        /// <remarks/>
        public string MagazynID {
            get {
                return this.magazynIDField;
            }
            set {
                this.magazynIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentRozchodowyDokumentObject {
        
        private int idField;
        
        private string numerField;
        
        private int kodBleduField;
        
        private string opisBleduField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Numer {
            get {
                return this.numerField;
            }
            set {
                this.numerField = value;
            }
        }
        
        /// <remarks/>
        public int KodBledu {
            get {
                return this.kodBleduField;
            }
            set {
                this.kodBleduField = value;
            }
        }
        
        /// <remarks/>
        public string OpisBledu {
            get {
                return this.opisBleduField;
            }
            set {
                this.opisBleduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentRozchodowyResult {
        
        private UtworzDokumentRozchodowyDokumentObject dokumentField;
        
        /// <remarks/>
        public UtworzDokumentRozchodowyDokumentObject Dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentRozchodowyRequestProduktObject {
        
        private string produktIDField;
        
        private decimal iloscField;
        
        private decimal cenaField;
        
        /// <remarks/>
        public string ProduktID {
            get {
                return this.produktIDField;
            }
            set {
                this.produktIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal Ilosc {
            get {
                return this.iloscField;
            }
            set {
                this.iloscField = value;
            }
        }
        
        /// <remarks/>
        public decimal Cena {
            get {
                return this.cenaField;
            }
            set {
                this.cenaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentRozchodowyRequestDataRequestObject {
        
        private int typDokumentuIDField;
        
        private string magazynIDField;
        
        private UtworzDokumentRozchodowyRequestProduktObject[] produktyField;
        
        /// <remarks/>
        public int TypDokumentuID {
            get {
                return this.typDokumentuIDField;
            }
            set {
                this.typDokumentuIDField = value;
            }
        }
        
        /// <remarks/>
        public string MagazynID {
            get {
                return this.magazynIDField;
            }
            set {
                this.magazynIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Produkt", IsNullable=false)]
        public UtworzDokumentRozchodowyRequestProduktObject[] Produkty {
            get {
                return this.produktyField;
            }
            set {
                this.produktyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class PobierzPotrawyProduktObject {
        
        private string produktIDField;
        
        private string indeksField;
        
        private string nazwaField;
        
        private string nazwaSkroconaField;
        
        private string jmField;
        
        private int dokladnoscField;
        
        /// <remarks/>
        public string ProduktID {
            get {
                return this.produktIDField;
            }
            set {
                this.produktIDField = value;
            }
        }
        
        /// <remarks/>
        public string Indeks {
            get {
                return this.indeksField;
            }
            set {
                this.indeksField = value;
            }
        }
        
        /// <remarks/>
        public string Nazwa {
            get {
                return this.nazwaField;
            }
            set {
                this.nazwaField = value;
            }
        }
        
        /// <remarks/>
        public string NazwaSkrocona {
            get {
                return this.nazwaSkroconaField;
            }
            set {
                this.nazwaSkroconaField = value;
            }
        }
        
        /// <remarks/>
        public string JM {
            get {
                return this.jmField;
            }
            set {
                this.jmField = value;
            }
        }
        
        /// <remarks/>
        public int Dokladnosc {
            get {
                return this.dokladnoscField;
            }
            set {
                this.dokladnoscField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class PobierzPotrawyResult {
        
        private PobierzPotrawyProduktObject[] produktyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Produkt", IsNullable=false)]
        public PobierzPotrawyProduktObject[] Produkty {
            get {
                return this.produktyField;
            }
            set {
                this.produktyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class PobierzPotrawyRequestDataRequestObject {
        
        private int grupaTowIDField;
        
        private string magazynIDField;
        
        /// <remarks/>
        public int GrupaTowID {
            get {
                return this.grupaTowIDField;
            }
            set {
                this.grupaTowIDField = value;
            }
        }
        
        /// <remarks/>
        public string MagazynID {
            get {
                return this.magazynIDField;
            }
            set {
                this.magazynIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class PobierzGrupyTowaroweGrupaTowarowaObject {
        
        private int idField;
        
        private string nazwaField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nazwa {
            get {
                return this.nazwaField;
            }
            set {
                this.nazwaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class PobierzGrupyTowaroweResult {
        
        private PobierzGrupyTowaroweGrupaTowarowaObject[] grupyTowaroweField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("GrupaTowarowa", IsNullable=false)]
        public PobierzGrupyTowaroweGrupaTowarowaObject[] GrupyTowarowe {
            get {
                return this.grupyTowaroweField;
            }
            set {
                this.grupyTowaroweField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class PobierzMagazynyMagazynObject {
        
        private string magazynIDField;
        
        private string symbolField;
        
        private string opisField;
        
        /// <remarks/>
        public string MagazynID {
            get {
                return this.magazynIDField;
            }
            set {
                this.magazynIDField = value;
            }
        }
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string Opis {
            get {
                return this.opisField;
            }
            set {
                this.opisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class PobierzMagazynyResult {
        
        private PobierzMagazynyMagazynObject[] magazynyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Magazyn", IsNullable=false)]
        public PobierzMagazynyMagazynObject[] Magazyny {
            get {
                return this.magazynyField;
            }
            set {
                this.magazynyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoDokumentObject {
        
        private int idField;
        
        private string numerField;
        
        private int kodBleduField;
        
        private string opisBleduField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Numer {
            get {
                return this.numerField;
            }
            set {
                this.numerField = value;
            }
        }
        
        /// <remarks/>
        public int KodBledu {
            get {
                return this.kodBleduField;
            }
            set {
                this.kodBleduField = value;
            }
        }
        
        /// <remarks/>
        public string OpisBledu {
            get {
                return this.opisBleduField;
            }
            set {
                this.opisBleduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoResult {
        
        private UtworzDokumentyPrzesunieciaMagazynowegoDokumentObject[] dokumentyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Dokument", IsNullable=false)]
        public UtworzDokumentyPrzesunieciaMagazynowegoDokumentObject[] Dokumenty {
            get {
                return this.dokumentyField;
            }
            set {
                this.dokumentyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoRequestProduktObject {
        
        private string produktIDField;
        
        private decimal iloscField;
        
        /// <remarks/>
        public string ProduktID {
            get {
                return this.produktIDField;
            }
            set {
                this.produktIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal Ilosc {
            get {
                return this.iloscField;
            }
            set {
                this.iloscField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoRequestDataRequestObject {
        
        private string magazynZrodlowyIDField;
        
        private string magazynDocelowyIDField;
        
        private UtworzDokumentyPrzesunieciaMagazynowegoRequestProduktObject[] produktyField;
        
        /// <remarks/>
        public string MagazynZrodlowyID {
            get {
                return this.magazynZrodlowyIDField;
            }
            set {
                this.magazynZrodlowyIDField = value;
            }
        }
        
        /// <remarks/>
        public string MagazynDocelowyID {
            get {
                return this.magazynDocelowyIDField;
            }
            set {
                this.magazynDocelowyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Produkt", IsNullable=false)]
        public UtworzDokumentyPrzesunieciaMagazynowegoRequestProduktObject[] Produkty {
            get {
                return this.produktyField;
            }
            set {
                this.produktyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentProdukcjiDokumentObject {
        
        private int idField;
        
        private string numerField;
        
        private int kodBleduField;
        
        private string opisBleduField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Numer {
            get {
                return this.numerField;
            }
            set {
                this.numerField = value;
            }
        }
        
        /// <remarks/>
        public int KodBledu {
            get {
                return this.kodBleduField;
            }
            set {
                this.kodBleduField = value;
            }
        }
        
        /// <remarks/>
        public string OpisBledu {
            get {
                return this.opisBleduField;
            }
            set {
                this.opisBleduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentProdukcjiResult {
        
        private UtworzDokumentProdukcjiDokumentObject dokumentField;
        
        /// <remarks/>
        public UtworzDokumentProdukcjiDokumentObject Dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentProdukcjiRequestProduktObject {
        
        private string produktIDField;
        
        private decimal iloscField;
        
        private decimal cenaField;
        
        /// <remarks/>
        public string ProduktID {
            get {
                return this.produktIDField;
            }
            set {
                this.produktIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal Ilosc {
            get {
                return this.iloscField;
            }
            set {
                this.iloscField = value;
            }
        }
        
        /// <remarks/>
        public decimal Cena {
            get {
                return this.cenaField;
            }
            set {
                this.cenaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class UtworzDokumentProdukcjiRequestDataRequestObject {
        
        private int typDokumentuIDField;
        
        private string magazynIDField;
        
        private UtworzDokumentProdukcjiRequestProduktObject[] produktyField;
        
        /// <remarks/>
        public int TypDokumentuID {
            get {
                return this.typDokumentuIDField;
            }
            set {
                this.typDokumentuIDField = value;
            }
        }
        
        /// <remarks/>
        public string MagazynID {
            get {
                return this.magazynIDField;
            }
            set {
                this.magazynIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Produkt", IsNullable=false)]
        public UtworzDokumentProdukcjiRequestProduktObject[] Produkty {
            get {
                return this.produktyField;
            }
            set {
                this.produktyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class PobierzProduktyProduktObject {
        
        private string produktIDField;
        
        private string indeksField;
        
        private string nazwaField;
        
        private string nazwaSkroconaField;
        
        private string jmField;
        
        private int dokladnoscField;
        
        private decimal stanField;
        
        /// <remarks/>
        public string ProduktID {
            get {
                return this.produktIDField;
            }
            set {
                this.produktIDField = value;
            }
        }
        
        /// <remarks/>
        public string Indeks {
            get {
                return this.indeksField;
            }
            set {
                this.indeksField = value;
            }
        }
        
        /// <remarks/>
        public string Nazwa {
            get {
                return this.nazwaField;
            }
            set {
                this.nazwaField = value;
            }
        }
        
        /// <remarks/>
        public string NazwaSkrocona {
            get {
                return this.nazwaSkroconaField;
            }
            set {
                this.nazwaSkroconaField = value;
            }
        }
        
        /// <remarks/>
        public string JM {
            get {
                return this.jmField;
            }
            set {
                this.jmField = value;
            }
        }
        
        /// <remarks/>
        public int Dokladnosc {
            get {
                return this.dokladnoscField;
            }
            set {
                this.dokladnoscField = value;
            }
        }
        
        /// <remarks/>
        public decimal Stan {
            get {
                return this.stanField;
            }
            set {
                this.stanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ICWS")]
    public partial class PobierzProduktyResult {
        
        private PobierzProduktyProduktObject[] produktyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Produkt", IsNullable=false)]
        public PobierzProduktyProduktObject[] Produkty {
            get {
                return this.produktyField;
            }
            set {
                this.produktyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PobierzProduktyCompletedEventHandler(object sender, PobierzProduktyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzProduktyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzProduktyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PobierzProduktyResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PobierzProduktyResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UtworzDokumentProdukcjiCompletedEventHandler(object sender, UtworzDokumentProdukcjiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UtworzDokumentProdukcjiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UtworzDokumentProdukcjiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UtworzDokumentProdukcjiResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UtworzDokumentProdukcjiResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UtworzDokumentyPrzesunieciaMagazynowegoCompletedEventHandler(object sender, UtworzDokumentyPrzesunieciaMagazynowegoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UtworzDokumentyPrzesunieciaMagazynowegoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UtworzDokumentyPrzesunieciaMagazynowegoResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UtworzDokumentyPrzesunieciaMagazynowegoResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PobierzMagazynyCompletedEventHandler(object sender, PobierzMagazynyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzMagazynyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzMagazynyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PobierzMagazynyResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PobierzMagazynyResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PobierzGrupyTowaroweCompletedEventHandler(object sender, PobierzGrupyTowaroweCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzGrupyTowaroweCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzGrupyTowaroweCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PobierzGrupyTowaroweResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PobierzGrupyTowaroweResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PobierzPotrawyCompletedEventHandler(object sender, PobierzPotrawyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzPotrawyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzPotrawyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PobierzPotrawyResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PobierzPotrawyResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UtworzDokumentRozchodowyCompletedEventHandler(object sender, UtworzDokumentRozchodowyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UtworzDokumentRozchodowyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UtworzDokumentRozchodowyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UtworzDokumentRozchodowyResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UtworzDokumentRozchodowyResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591