//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LsiService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PobierzProduktyRequestDataRequestObject", Namespace = "ICWS")]
    public partial class PobierzProduktyRequestDataRequestObject : object
    {

        private int GrupaTowIDField;

        private string MagazynIDField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int GrupaTowID
        {
            get
            {
                return this.GrupaTowIDField;
            }
            set
            {
                this.GrupaTowIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string MagazynID
        {
            get
            {
                return this.MagazynIDField;
            }
            set
            {
                this.MagazynIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PobierzProduktyResult", Namespace = "ICWS")]
    public partial class PobierzProduktyResult : object
    {

        private LsiService.ArrayOfPobierzProduktyProduktObject ProduktyField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public LsiService.ArrayOfPobierzProduktyProduktObject Produkty
        {
            get
            {
                return this.ProduktyField;
            }
            set
            {
                this.ProduktyField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfPobierzProduktyProduktObject", Namespace = "ICWS", ItemName = "Produkt")]
    public class ArrayOfPobierzProduktyProduktObject : System.Collections.Generic.List<LsiService.PobierzProduktyProduktObject>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PobierzProduktyProduktObject", Namespace = "ICWS")]
    public partial class PobierzProduktyProduktObject : object
    {

        private string ProduktIDField;

        private string IndeksField;

        private string NazwaField;

        private string NazwaSkroconaField;

        private string JMField;

        private int DokladnoscField;

        private decimal StanField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string ProduktID
        {
            get
            {
                return this.ProduktIDField;
            }
            set
            {
                this.ProduktIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Indeks
        {
            get
            {
                return this.IndeksField;
            }
            set
            {
                this.IndeksField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string NazwaSkrocona
        {
            get
            {
                return this.NazwaSkroconaField;
            }
            set
            {
                this.NazwaSkroconaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string JM
        {
            get
            {
                return this.JMField;
            }
            set
            {
                this.JMField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public int Dokladnosc
        {
            get
            {
                return this.DokladnoscField;
            }
            set
            {
                this.DokladnoscField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 6)]
        public decimal Stan
        {
            get
            {
                return this.StanField;
            }
            set
            {
                this.StanField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentProdukcjiRequestDataRequestObject", Namespace = "ICWS")]
    public partial class UtworzDokumentProdukcjiRequestDataRequestObject : object
    {

        private int TypDokumentuIDField;

        private string MagazynIDField;

        private LsiService.ArrayOfUtworzDokumentProdukcjiRequestProduktObject ProduktyField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int TypDokumentuID
        {
            get
            {
                return this.TypDokumentuIDField;
            }
            set
            {
                this.TypDokumentuIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string MagazynID
        {
            get
            {
                return this.MagazynIDField;
            }
            set
            {
                this.MagazynIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public LsiService.ArrayOfUtworzDokumentProdukcjiRequestProduktObject Produkty
        {
            get
            {
                return this.ProduktyField;
            }
            set
            {
                this.ProduktyField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfUtworzDokumentProdukcjiRequestProduktObject", Namespace = "ICWS", ItemName = "Produkt")]
    public class ArrayOfUtworzDokumentProdukcjiRequestProduktObject : System.Collections.Generic.List<LsiService.UtworzDokumentProdukcjiRequestProduktObject>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentProdukcjiRequestProduktObject", Namespace = "ICWS")]
    public partial class UtworzDokumentProdukcjiRequestProduktObject : object
    {

        private string ProduktIDField;

        private decimal IloscField;

        private decimal CenaField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string ProduktID
        {
            get
            {
                return this.ProduktIDField;
            }
            set
            {
                this.ProduktIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public decimal Ilosc
        {
            get
            {
                return this.IloscField;
            }
            set
            {
                this.IloscField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public decimal Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentProdukcjiResult", Namespace = "ICWS")]
    public partial class UtworzDokumentProdukcjiResult : object
    {

        private LsiService.UtworzDokumentProdukcjiDokumentObject DokumentField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public LsiService.UtworzDokumentProdukcjiDokumentObject Dokument
        {
            get
            {
                return this.DokumentField;
            }
            set
            {
                this.DokumentField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentProdukcjiDokumentObject", Namespace = "ICWS")]
    public partial class UtworzDokumentProdukcjiDokumentObject : object
    {

        private int IDField;

        private string NumerField;

        private int KodBleduField;

        private string OpisBleduField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Numer
        {
            get
            {
                return this.NumerField;
            }
            set
            {
                this.NumerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public int KodBledu
        {
            get
            {
                return this.KodBleduField;
            }
            set
            {
                this.KodBleduField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string OpisBledu
        {
            get
            {
                return this.OpisBleduField;
            }
            set
            {
                this.OpisBleduField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentyPrzesunieciaMagazynowegoRequestDataRequestObject", Namespace = "ICWS")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoRequestDataRequestObject : object
    {

        private string MagazynZrodlowyIDField;

        private string MagazynDocelowyIDField;

        private LsiService.ArrayOfUtworzDokumentyPrzesunieciaMagazynowegoRequestProduktObject ProduktyField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string MagazynZrodlowyID
        {
            get
            {
                return this.MagazynZrodlowyIDField;
            }
            set
            {
                this.MagazynZrodlowyIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string MagazynDocelowyID
        {
            get
            {
                return this.MagazynDocelowyIDField;
            }
            set
            {
                this.MagazynDocelowyIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public LsiService.ArrayOfUtworzDokumentyPrzesunieciaMagazynowegoRequestProduktObject Produkty
        {
            get
            {
                return this.ProduktyField;
            }
            set
            {
                this.ProduktyField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfUtworzDokumentyPrzesunieciaMagazynowegoRequestProduktObject", Namespace = "ICWS", ItemName = "Produkt")]
    public class ArrayOfUtworzDokumentyPrzesunieciaMagazynowegoRequestProduktObject : System.Collections.Generic.List<LsiService.UtworzDokumentyPrzesunieciaMagazynowegoRequestProduktObject>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentyPrzesunieciaMagazynowegoRequestProduktObject", Namespace = "ICWS")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoRequestProduktObject : object
    {

        private string ProduktIDField;

        private decimal IloscField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string ProduktID
        {
            get
            {
                return this.ProduktIDField;
            }
            set
            {
                this.ProduktIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public decimal Ilosc
        {
            get
            {
                return this.IloscField;
            }
            set
            {
                this.IloscField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentyPrzesunieciaMagazynowegoResult", Namespace = "ICWS")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoResult : object
    {

        private LsiService.ArrayOfUtworzDokumentyPrzesunieciaMagazynowegoDokumentObject DokumentyField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public LsiService.ArrayOfUtworzDokumentyPrzesunieciaMagazynowegoDokumentObject Dokumenty
        {
            get
            {
                return this.DokumentyField;
            }
            set
            {
                this.DokumentyField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfUtworzDokumentyPrzesunieciaMagazynowegoDokumentObject", Namespace = "ICWS", ItemName = "Dokument")]
    public class ArrayOfUtworzDokumentyPrzesunieciaMagazynowegoDokumentObject : System.Collections.Generic.List<LsiService.UtworzDokumentyPrzesunieciaMagazynowegoDokumentObject>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentyPrzesunieciaMagazynowegoDokumentObject", Namespace = "ICWS")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoDokumentObject : object
    {

        private int IDField;

        private string NumerField;

        private int KodBleduField;

        private string OpisBleduField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Numer
        {
            get
            {
                return this.NumerField;
            }
            set
            {
                this.NumerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public int KodBledu
        {
            get
            {
                return this.KodBleduField;
            }
            set
            {
                this.KodBleduField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string OpisBledu
        {
            get
            {
                return this.OpisBleduField;
            }
            set
            {
                this.OpisBleduField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PobierzMagazynyResult", Namespace = "ICWS")]
    public partial class PobierzMagazynyResult : object
    {

        private LsiService.ArrayOfPobierzMagazynyMagazynObject MagazynyField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public LsiService.ArrayOfPobierzMagazynyMagazynObject Magazyny
        {
            get
            {
                return this.MagazynyField;
            }
            set
            {
                this.MagazynyField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfPobierzMagazynyMagazynObject", Namespace = "ICWS", ItemName = "Magazyn")]
    public class ArrayOfPobierzMagazynyMagazynObject : System.Collections.Generic.List<LsiService.PobierzMagazynyMagazynObject>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PobierzMagazynyMagazynObject", Namespace = "ICWS")]
    public partial class PobierzMagazynyMagazynObject : object
    {

        private string MagazynIDField;

        private string SymbolField;

        private string OpisField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string MagazynID
        {
            get
            {
                return this.MagazynIDField;
            }
            set
            {
                this.MagazynIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PobierzGrupyTowaroweResult", Namespace = "ICWS")]
    public partial class PobierzGrupyTowaroweResult : object
    {

        private LsiService.ArrayOfPobierzGrupyTowaroweGrupaTowarowaObject GrupyTowaroweField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public LsiService.ArrayOfPobierzGrupyTowaroweGrupaTowarowaObject GrupyTowarowe
        {
            get
            {
                return this.GrupyTowaroweField;
            }
            set
            {
                this.GrupyTowaroweField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfPobierzGrupyTowaroweGrupaTowarowaObject", Namespace = "ICWS", ItemName = "GrupaTowarowa")]
    public class ArrayOfPobierzGrupyTowaroweGrupaTowarowaObject : System.Collections.Generic.List<LsiService.PobierzGrupyTowaroweGrupaTowarowaObject>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PobierzGrupyTowaroweGrupaTowarowaObject", Namespace = "ICWS")]
    public partial class PobierzGrupyTowaroweGrupaTowarowaObject : object
    {

        private int IDField;

        private string NazwaField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PobierzPotrawyRequestDataRequestObject", Namespace = "ICWS")]
    public partial class PobierzPotrawyRequestDataRequestObject : object
    {

        private int GrupaTowIDField;

        private string MagazynIDField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int GrupaTowID
        {
            get
            {
                return this.GrupaTowIDField;
            }
            set
            {
                this.GrupaTowIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string MagazynID
        {
            get
            {
                return this.MagazynIDField;
            }
            set
            {
                this.MagazynIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PobierzPotrawyResult", Namespace = "ICWS")]
    public partial class PobierzPotrawyResult : object
    {

        private LsiService.ArrayOfPobierzPotrawyProduktObject ProduktyField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public LsiService.ArrayOfPobierzPotrawyProduktObject Produkty
        {
            get
            {
                return this.ProduktyField;
            }
            set
            {
                this.ProduktyField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfPobierzPotrawyProduktObject", Namespace = "ICWS", ItemName = "Produkt")]
    public class ArrayOfPobierzPotrawyProduktObject : System.Collections.Generic.List<LsiService.PobierzPotrawyProduktObject>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PobierzPotrawyProduktObject", Namespace = "ICWS")]
    public partial class PobierzPotrawyProduktObject : object
    {

        private string ProduktIDField;

        private string IndeksField;

        private string NazwaField;

        private string NazwaSkroconaField;

        private string JMField;

        private int DokladnoscField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string ProduktID
        {
            get
            {
                return this.ProduktIDField;
            }
            set
            {
                this.ProduktIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Indeks
        {
            get
            {
                return this.IndeksField;
            }
            set
            {
                this.IndeksField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string NazwaSkrocona
        {
            get
            {
                return this.NazwaSkroconaField;
            }
            set
            {
                this.NazwaSkroconaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string JM
        {
            get
            {
                return this.JMField;
            }
            set
            {
                this.JMField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public int Dokladnosc
        {
            get
            {
                return this.DokladnoscField;
            }
            set
            {
                this.DokladnoscField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentRozchodowyRequestDataRequestObject", Namespace = "ICWS")]
    public partial class UtworzDokumentRozchodowyRequestDataRequestObject : object
    {

        private int TypDokumentuIDField;

        private string MagazynIDField;

        private LsiService.ArrayOfUtworzDokumentRozchodowyRequestProduktObject ProduktyField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int TypDokumentuID
        {
            get
            {
                return this.TypDokumentuIDField;
            }
            set
            {
                this.TypDokumentuIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string MagazynID
        {
            get
            {
                return this.MagazynIDField;
            }
            set
            {
                this.MagazynIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public LsiService.ArrayOfUtworzDokumentRozchodowyRequestProduktObject Produkty
        {
            get
            {
                return this.ProduktyField;
            }
            set
            {
                this.ProduktyField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfUtworzDokumentRozchodowyRequestProduktObject", Namespace = "ICWS", ItemName = "Produkt")]
    public class ArrayOfUtworzDokumentRozchodowyRequestProduktObject : System.Collections.Generic.List<LsiService.UtworzDokumentRozchodowyRequestProduktObject>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentRozchodowyRequestProduktObject", Namespace = "ICWS")]
    public partial class UtworzDokumentRozchodowyRequestProduktObject : object
    {

        private string ProduktIDField;

        private decimal IloscField;

        private decimal CenaField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string ProduktID
        {
            get
            {
                return this.ProduktIDField;
            }
            set
            {
                this.ProduktIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public decimal Ilosc
        {
            get
            {
                return this.IloscField;
            }
            set
            {
                this.IloscField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public decimal Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentRozchodowyResult", Namespace = "ICWS")]
    public partial class UtworzDokumentRozchodowyResult : object
    {

        private LsiService.UtworzDokumentRozchodowyDokumentObject DokumentField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public LsiService.UtworzDokumentRozchodowyDokumentObject Dokument
        {
            get
            {
                return this.DokumentField;
            }
            set
            {
                this.DokumentField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UtworzDokumentRozchodowyDokumentObject", Namespace = "ICWS")]
    public partial class UtworzDokumentRozchodowyDokumentObject : object
    {

        private int IDField;

        private string NumerField;

        private int KodBleduField;

        private string OpisBleduField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Numer
        {
            get
            {
                return this.NumerField;
            }
            set
            {
                this.NumerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public int KodBledu
        {
            get
            {
                return this.KodBleduField;
            }
            set
            {
                this.KodBleduField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string OpisBledu
        {
            get
            {
                return this.OpisBleduField;
            }
            set
            {
                this.OpisBleduField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "ICWS", ConfigurationName = "LsiService.ICWSSoap")]
    public interface ICWSSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSPobierzProdukty", ReplyAction = "*")]
        LsiService.PobierzProduktyResponse PobierzProdukty(LsiService.PobierzProduktyRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSPobierzProdukty", ReplyAction = "*")]
        System.Threading.Tasks.Task<LsiService.PobierzProduktyResponse> PobierzProduktyAsync(LsiService.PobierzProduktyRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSUtworzDokumentProdukcji", ReplyAction = "*")]
        LsiService.UtworzDokumentProdukcjiResponse UtworzDokumentProdukcji(LsiService.UtworzDokumentProdukcjiRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSUtworzDokumentProdukcji", ReplyAction = "*")]
        System.Threading.Tasks.Task<LsiService.UtworzDokumentProdukcjiResponse> UtworzDokumentProdukcjiAsync(LsiService.UtworzDokumentProdukcjiRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSUtworzDokumentyPrzesunieciaMagazynowego", ReplyAction = "*")]
        LsiService.UtworzDokumentyPrzesunieciaMagazynowegoResponse UtworzDokumentyPrzesunieciaMagazynowego(LsiService.UtworzDokumentyPrzesunieciaMagazynowegoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSUtworzDokumentyPrzesunieciaMagazynowego", ReplyAction = "*")]
        System.Threading.Tasks.Task<LsiService.UtworzDokumentyPrzesunieciaMagazynowegoResponse> UtworzDokumentyPrzesunieciaMagazynowegoAsync(LsiService.UtworzDokumentyPrzesunieciaMagazynowegoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSPobierzMagazyny", ReplyAction = "*")]
        LsiService.PobierzMagazynyResponse PobierzMagazyny(LsiService.PobierzMagazynyRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSPobierzMagazyny", ReplyAction = "*")]
        System.Threading.Tasks.Task<LsiService.PobierzMagazynyResponse> PobierzMagazynyAsync(LsiService.PobierzMagazynyRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSPobierzGrupyTowarowe", ReplyAction = "*")]
        LsiService.PobierzGrupyTowaroweResponse PobierzGrupyTowarowe(LsiService.PobierzGrupyTowaroweRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSPobierzGrupyTowarowe", ReplyAction = "*")]
        System.Threading.Tasks.Task<LsiService.PobierzGrupyTowaroweResponse> PobierzGrupyTowaroweAsync(LsiService.PobierzGrupyTowaroweRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSPobierzPotrawy", ReplyAction = "*")]
        LsiService.PobierzPotrawyResponse PobierzPotrawy(LsiService.PobierzPotrawyRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSPobierzPotrawy", ReplyAction = "*")]
        System.Threading.Tasks.Task<LsiService.PobierzPotrawyResponse> PobierzPotrawyAsync(LsiService.PobierzPotrawyRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSUtworzDokumentRozchodowy", ReplyAction = "*")]
        LsiService.UtworzDokumentRozchodowyResponse UtworzDokumentRozchodowy(LsiService.UtworzDokumentRozchodowyRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "ICWSUtworzDokumentRozchodowy", ReplyAction = "*")]
        System.Threading.Tasks.Task<LsiService.UtworzDokumentRozchodowyResponse> UtworzDokumentRozchodowyAsync(LsiService.UtworzDokumentRozchodowyRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PobierzProduktyRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PobierzProdukty", Namespace = "ICWS", Order = 0)]
        public LsiService.PobierzProduktyRequestBody Body;

        public PobierzProduktyRequest()
        {
        }

        public PobierzProduktyRequest(LsiService.PobierzProduktyRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class PobierzProduktyRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.PobierzProduktyRequestDataRequestObject RequestData;

        public PobierzProduktyRequestBody()
        {
        }

        public PobierzProduktyRequestBody(LsiService.PobierzProduktyRequestDataRequestObject RequestData)
        {
            this.RequestData = RequestData;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PobierzProduktyResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PobierzProduktyResponse", Namespace = "ICWS", Order = 0)]
        public LsiService.PobierzProduktyResponseBody Body;

        public PobierzProduktyResponse()
        {
        }

        public PobierzProduktyResponse(LsiService.PobierzProduktyResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class PobierzProduktyResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.PobierzProduktyResult PobierzProduktyResult;

        public PobierzProduktyResponseBody()
        {
        }

        public PobierzProduktyResponseBody(LsiService.PobierzProduktyResult PobierzProduktyResult)
        {
            this.PobierzProduktyResult = PobierzProduktyResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class UtworzDokumentProdukcjiRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "UtworzDokumentProdukcji", Namespace = "ICWS", Order = 0)]
        public LsiService.UtworzDokumentProdukcjiRequestBody Body;

        public UtworzDokumentProdukcjiRequest()
        {
        }

        public UtworzDokumentProdukcjiRequest(LsiService.UtworzDokumentProdukcjiRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class UtworzDokumentProdukcjiRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.UtworzDokumentProdukcjiRequestDataRequestObject RequestData;

        public UtworzDokumentProdukcjiRequestBody()
        {
        }

        public UtworzDokumentProdukcjiRequestBody(LsiService.UtworzDokumentProdukcjiRequestDataRequestObject RequestData)
        {
            this.RequestData = RequestData;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class UtworzDokumentProdukcjiResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "UtworzDokumentProdukcjiResponse", Namespace = "ICWS", Order = 0)]
        public LsiService.UtworzDokumentProdukcjiResponseBody Body;

        public UtworzDokumentProdukcjiResponse()
        {
        }

        public UtworzDokumentProdukcjiResponse(LsiService.UtworzDokumentProdukcjiResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class UtworzDokumentProdukcjiResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.UtworzDokumentProdukcjiResult UtworzDokumentProdukcjiResult;

        public UtworzDokumentProdukcjiResponseBody()
        {
        }

        public UtworzDokumentProdukcjiResponseBody(LsiService.UtworzDokumentProdukcjiResult UtworzDokumentProdukcjiResult)
        {
            this.UtworzDokumentProdukcjiResult = UtworzDokumentProdukcjiResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "UtworzDokumentyPrzesunieciaMagazynowego", Namespace = "ICWS", Order = 0)]
        public LsiService.UtworzDokumentyPrzesunieciaMagazynowegoRequestBody Body;

        public UtworzDokumentyPrzesunieciaMagazynowegoRequest()
        {
        }

        public UtworzDokumentyPrzesunieciaMagazynowegoRequest(LsiService.UtworzDokumentyPrzesunieciaMagazynowegoRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.UtworzDokumentyPrzesunieciaMagazynowegoRequestDataRequestObject RequestData;

        public UtworzDokumentyPrzesunieciaMagazynowegoRequestBody()
        {
        }

        public UtworzDokumentyPrzesunieciaMagazynowegoRequestBody(LsiService.UtworzDokumentyPrzesunieciaMagazynowegoRequestDataRequestObject RequestData)
        {
            this.RequestData = RequestData;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "UtworzDokumentyPrzesunieciaMagazynowegoResponse", Namespace = "ICWS", Order = 0)]
        public LsiService.UtworzDokumentyPrzesunieciaMagazynowegoResponseBody Body;

        public UtworzDokumentyPrzesunieciaMagazynowegoResponse()
        {
        }

        public UtworzDokumentyPrzesunieciaMagazynowegoResponse(LsiService.UtworzDokumentyPrzesunieciaMagazynowegoResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class UtworzDokumentyPrzesunieciaMagazynowegoResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.UtworzDokumentyPrzesunieciaMagazynowegoResult UtworzDokumentyPrzesunieciaMagazynowegoResult;

        public UtworzDokumentyPrzesunieciaMagazynowegoResponseBody()
        {
        }

        public UtworzDokumentyPrzesunieciaMagazynowegoResponseBody(LsiService.UtworzDokumentyPrzesunieciaMagazynowegoResult UtworzDokumentyPrzesunieciaMagazynowegoResult)
        {
            this.UtworzDokumentyPrzesunieciaMagazynowegoResult = UtworzDokumentyPrzesunieciaMagazynowegoResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PobierzMagazynyRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PobierzMagazyny", Namespace = "ICWS", Order = 0)]
        public LsiService.PobierzMagazynyRequestBody Body;

        public PobierzMagazynyRequest()
        {
        }

        public PobierzMagazynyRequest(LsiService.PobierzMagazynyRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PobierzMagazynyRequestBody
    {

        public PobierzMagazynyRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PobierzMagazynyResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PobierzMagazynyResponse", Namespace = "ICWS", Order = 0)]
        public LsiService.PobierzMagazynyResponseBody Body;

        public PobierzMagazynyResponse()
        {
        }

        public PobierzMagazynyResponse(LsiService.PobierzMagazynyResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class PobierzMagazynyResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.PobierzMagazynyResult PobierzMagazynyResult;

        public PobierzMagazynyResponseBody()
        {
        }

        public PobierzMagazynyResponseBody(LsiService.PobierzMagazynyResult PobierzMagazynyResult)
        {
            this.PobierzMagazynyResult = PobierzMagazynyResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PobierzGrupyTowaroweRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PobierzGrupyTowarowe", Namespace = "ICWS", Order = 0)]
        public LsiService.PobierzGrupyTowaroweRequestBody Body;

        public PobierzGrupyTowaroweRequest()
        {
        }

        public PobierzGrupyTowaroweRequest(LsiService.PobierzGrupyTowaroweRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PobierzGrupyTowaroweRequestBody
    {

        public PobierzGrupyTowaroweRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PobierzGrupyTowaroweResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PobierzGrupyTowaroweResponse", Namespace = "ICWS", Order = 0)]
        public LsiService.PobierzGrupyTowaroweResponseBody Body;

        public PobierzGrupyTowaroweResponse()
        {
        }

        public PobierzGrupyTowaroweResponse(LsiService.PobierzGrupyTowaroweResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class PobierzGrupyTowaroweResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.PobierzGrupyTowaroweResult PobierzGrupyTowaroweResult;

        public PobierzGrupyTowaroweResponseBody()
        {
        }

        public PobierzGrupyTowaroweResponseBody(LsiService.PobierzGrupyTowaroweResult PobierzGrupyTowaroweResult)
        {
            this.PobierzGrupyTowaroweResult = PobierzGrupyTowaroweResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PobierzPotrawyRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PobierzPotrawy", Namespace = "ICWS", Order = 0)]
        public LsiService.PobierzPotrawyRequestBody Body;

        public PobierzPotrawyRequest()
        {
        }

        public PobierzPotrawyRequest(LsiService.PobierzPotrawyRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class PobierzPotrawyRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.PobierzPotrawyRequestDataRequestObject RequestData;

        public PobierzPotrawyRequestBody()
        {
        }

        public PobierzPotrawyRequestBody(LsiService.PobierzPotrawyRequestDataRequestObject RequestData)
        {
            this.RequestData = RequestData;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PobierzPotrawyResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PobierzPotrawyResponse", Namespace = "ICWS", Order = 0)]
        public LsiService.PobierzPotrawyResponseBody Body;

        public PobierzPotrawyResponse()
        {
        }

        public PobierzPotrawyResponse(LsiService.PobierzPotrawyResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class PobierzPotrawyResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.PobierzPotrawyResult PobierzPotrawyResult;

        public PobierzPotrawyResponseBody()
        {
        }

        public PobierzPotrawyResponseBody(LsiService.PobierzPotrawyResult PobierzPotrawyResult)
        {
            this.PobierzPotrawyResult = PobierzPotrawyResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class UtworzDokumentRozchodowyRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "UtworzDokumentRozchodowy", Namespace = "ICWS", Order = 0)]
        public LsiService.UtworzDokumentRozchodowyRequestBody Body;

        public UtworzDokumentRozchodowyRequest()
        {
        }

        public UtworzDokumentRozchodowyRequest(LsiService.UtworzDokumentRozchodowyRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class UtworzDokumentRozchodowyRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.UtworzDokumentRozchodowyRequestDataRequestObject RequestData;

        public UtworzDokumentRozchodowyRequestBody()
        {
        }

        public UtworzDokumentRozchodowyRequestBody(LsiService.UtworzDokumentRozchodowyRequestDataRequestObject RequestData)
        {
            this.RequestData = RequestData;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class UtworzDokumentRozchodowyResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "UtworzDokumentRozchodowyResponse", Namespace = "ICWS", Order = 0)]
        public LsiService.UtworzDokumentRozchodowyResponseBody Body;

        public UtworzDokumentRozchodowyResponse()
        {
        }

        public UtworzDokumentRozchodowyResponse(LsiService.UtworzDokumentRozchodowyResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "ICWS")]
    public partial class UtworzDokumentRozchodowyResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public LsiService.UtworzDokumentRozchodowyResult UtworzDokumentRozchodowyResult;

        public UtworzDokumentRozchodowyResponseBody()
        {
        }

        public UtworzDokumentRozchodowyResponseBody(LsiService.UtworzDokumentRozchodowyResult UtworzDokumentRozchodowyResult)
        {
            this.UtworzDokumentRozchodowyResult = UtworzDokumentRozchodowyResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ICWSSoapChannel : LsiService.ICWSSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CWSSoapClient : System.ServiceModel.ClientBase<LsiService.ICWSSoap>, LsiService.ICWSSoap
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public CWSSoapClient(EndpointConfiguration endpointConfiguration) :
                base(CWSSoapClient.GetBindingForEndpoint(endpointConfiguration), CWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(CWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(CWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public LsiService.PobierzProduktyResponse PobierzProdukty(LsiService.PobierzProduktyRequest request)
        {
            return base.Channel.PobierzProdukty(request);
        }

        public System.Threading.Tasks.Task<LsiService.PobierzProduktyResponse> PobierzProduktyAsync(LsiService.PobierzProduktyRequest request)
        {
            return base.Channel.PobierzProduktyAsync(request);
        }

        public LsiService.UtworzDokumentProdukcjiResponse UtworzDokumentProdukcji(LsiService.UtworzDokumentProdukcjiRequest request)
        {
            return base.Channel.UtworzDokumentProdukcji(request);
        }

        public System.Threading.Tasks.Task<LsiService.UtworzDokumentProdukcjiResponse> UtworzDokumentProdukcjiAsync(LsiService.UtworzDokumentProdukcjiRequest request)
        {
            return base.Channel.UtworzDokumentProdukcjiAsync(request);
        }

        public LsiService.UtworzDokumentyPrzesunieciaMagazynowegoResponse UtworzDokumentyPrzesunieciaMagazynowego(LsiService.UtworzDokumentyPrzesunieciaMagazynowegoRequest request)
        {
            return base.Channel.UtworzDokumentyPrzesunieciaMagazynowego(request);
        }

        public System.Threading.Tasks.Task<LsiService.UtworzDokumentyPrzesunieciaMagazynowegoResponse> UtworzDokumentyPrzesunieciaMagazynowegoAsync(LsiService.UtworzDokumentyPrzesunieciaMagazynowegoRequest request)
        {
            return base.Channel.UtworzDokumentyPrzesunieciaMagazynowegoAsync(request);
        }

        public LsiService.PobierzMagazynyResponse PobierzMagazyny(LsiService.PobierzMagazynyRequest request)
        {
            return base.Channel.PobierzMagazyny(request);
        }

        public System.Threading.Tasks.Task<LsiService.PobierzMagazynyResponse> PobierzMagazynyAsync(LsiService.PobierzMagazynyRequest request)
        {
            return base.Channel.PobierzMagazynyAsync(request);
        }

        public LsiService.PobierzGrupyTowaroweResponse PobierzGrupyTowarowe(LsiService.PobierzGrupyTowaroweRequest request)
        {
            return base.Channel.PobierzGrupyTowarowe(request);
        }

        public System.Threading.Tasks.Task<LsiService.PobierzGrupyTowaroweResponse> PobierzGrupyTowaroweAsync(LsiService.PobierzGrupyTowaroweRequest request)
        {
            return base.Channel.PobierzGrupyTowaroweAsync(request);
        }

        public LsiService.PobierzPotrawyResponse PobierzPotrawy(LsiService.PobierzPotrawyRequest request)
        {
            return base.Channel.PobierzPotrawy(request);
        }

        public System.Threading.Tasks.Task<LsiService.PobierzPotrawyResponse> PobierzPotrawyAsync(LsiService.PobierzPotrawyRequest request)
        {
            return base.Channel.PobierzPotrawyAsync(request);
        }

        public LsiService.UtworzDokumentRozchodowyResponse UtworzDokumentRozchodowy(LsiService.UtworzDokumentRozchodowyRequest request)
        {
            return base.Channel.UtworzDokumentRozchodowy(request);
        }

        public System.Threading.Tasks.Task<LsiService.UtworzDokumentRozchodowyResponse> UtworzDokumentRozchodowyAsync(LsiService.UtworzDokumentRozchodowyRequest request)
        {
            return base.Channel.UtworzDokumentRozchodowyAsync(request);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ICWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.SendTimeout = new System.TimeSpan(0, 5, 0);
                result.ReceiveTimeout = new System.TimeSpan(0, 5, 0);
                result.OpenTimeout = new System.TimeSpan(0, 5, 0);
                result.CloseTimeout = new System.TimeSpan(0, 5, 0);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ICWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                result.SendTimeout = new System.TimeSpan(0, 5, 0);
                result.ReceiveTimeout = new System.TimeSpan(0, 5, 0);
                result.OpenTimeout = new System.TimeSpan(0, 5, 0);
                result.CloseTimeout = new System.TimeSpan(0, 5, 0);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ICWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.81.70:8089/icws.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ICWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.81.70:8089/icws.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            ICWSSoap,

            ICWSSoap12,
        }
    }
}
